name: LAB4architecture.com
favicon: null
layout_spectrum: 0.94124
typography_spectrum: 0.48936
title: Laboratory for Architecture and Building
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1f21'
    - '#ffffff'
    - '#63665b'
    - '#bd9e70'
    - '#1a5c74'
  brandStrength: 0.6749194010626525
  lightness: 0.7952514705248177
  saturation: 0.4045174594502896
  rhythmicContrast: 0.5430668569169939
purpose: []
