name: LAB4architecture.com
favicon: null
layout_spectrum: 0.11600712779909372
typography_spectrum: 0.5122520672157407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6749194010626525
  lightness: 0.7952514705248177
  saturation: 0.4045174594502896
  rhythmicContrast: 0.5430668569169939
purpose: []
